---@class SentinelErrorCodes
local ErrorCodes = {
    OK = "OK",

    -- Core lifecycle/config
    GAME_VERSION_UNSUPPORTED = "GAME_VERSION_UNSUPPORTED",
    STATE_TRANSITION_INVALID = "STATE_TRANSITION_INVALID",
    MODE_NOT_AVAILABLE = "MODE_NOT_AVAILABLE",
    MODE_CAN_ENTER_FAILED = "MODE_CAN_ENTER_FAILED",
    CONFIG_INVALID = "CONFIG_INVALID",
    CONFIG_SCHEMA_INVALID = "CONFIG_SCHEMA_INVALID",
    CONFIG_SCHEMA_VERSION_INVALID = "CONFIG_SCHEMA_VERSION_INVALID",
    POLICY_IO_ERROR = "POLICY_IO_ERROR",
    PERSISTENCE_CORRUPTED = "PERSISTENCE_CORRUPTED",
    PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND",
    PROFILE_DELETE_LAST = "PROFILE_DELETE_LAST",

    -- Dependencies
    DEP_NAVCLIENT_MISSING = "DEP_NAVCLIENT_MISSING",
    DEP_NAVCLIENT_UNHEALTHY = "DEP_NAVCLIENT_UNHEALTHY",
    DEP_WORLDDATA_UNAVAILABLE = "DEP_WORLDDATA_UNAVAILABLE",
    DEP_WORLDDATA_DATASET_MISMATCH = "DEP_WORLDDATA_DATASET_MISMATCH",

    -- Context and world data
    CTX_UNRESOLVED = "CTX_UNRESOLVED",
    CTX_LOW_CONFIDENCE = "CTX_LOW_CONFIDENCE",
    MAP_NOT_SUPPORTED = "MAP_NOT_SUPPORTED",
    INVALID_PARAMS = "INVALID_PARAMS",
    INTERNAL_ERROR = "INTERNAL_ERROR",

    -- Target/combat/loot
    TARGET_NOT_FOUND = "TARGET_NOT_FOUND",
    TARGET_LOST = "TARGET_LOST",
    PULL_FAILED = "PULL_FAILED",
    MAINTENANCE_REQUIRED = "MAINTENANCE_REQUIRED",
    COMBAT_TIMEOUT = "COMBAT_TIMEOUT",
    ACTION_TIMEOUT = "ACTION_TIMEOUT",
    ROTATION_UNAVAILABLE = "ROTATION_UNAVAILABLE",
    CAST_GUARD_BLOCKED = "CAST_GUARD_BLOCKED",
    CAST_INVALID_TARGET = "CAST_INVALID_TARGET",
    OBJECTIVE_NONE_AVAILABLE = "OBJECTIVE_NONE_AVAILABLE",
    OBJECTIVE_PROVIDER_INVALID = "OBJECTIVE_PROVIDER_INVALID",
    OBJECTIVE_EXECUTION_FAILED = "OBJECTIVE_EXECUTION_FAILED",
    LOOT_TIMEOUT = "LOOT_TIMEOUT",
    LOOT_FAILED = "LOOT_FAILED",

    -- Inventory/vendor
    INVENTORY_THRESHOLD_REACHED = "INVENTORY_THRESHOLD_REACHED",
    INVENTORY_POLICY_INVALID = "INVENTORY_POLICY_INVALID",
    VENDOR_REQUIRED = "VENDOR_REQUIRED",
    VENDOR_FETCH_FAILED = "VENDOR_FETCH_FAILED",
    VENDOR_SAME_MAP_REQUIRED = "VENDOR_SAME_MAP_REQUIRED",
    VENDOR_CAPABILITY_MISSING = "VENDOR_CAPABILITY_MISSING",
    VENDOR_FACTION_MISMATCH = "VENDOR_FACTION_MISMATCH",
    VENDOR_UNREACHABLE = "VENDOR_UNREACHABLE",
    VENDOR_NONE_VIABLE = "VENDOR_NONE_VIABLE",
    VENDOR_INTERACTION_TIMEOUT = "VENDOR_INTERACTION_TIMEOUT",

    -- Navigation
    NAV_MOVE_FAILED = "NAV_MOVE_FAILED",

    -- Recovery
    RECOVERY_PAUSED = "RECOVERY_PAUSED",
    RECOVERY_RESTARTING = "RECOVERY_RESTARTING",
    RECOVERY_ATTEMPTS_EXHAUSTED = "RECOVERY_ATTEMPTS_EXHAUSTED",
}

return ErrorCodes
