//! Raw FFI bindings to Recast/Detour navigation library.
//!
//! This crate provides unsafe C bindings generated by bindgen from our
//! C wrapper layer. Use the `detour` crate for safe Rust wrappers.
//!
//! ## Safety
//!
//! All functions in this crate are `unsafe` and require careful handling:
//! - Pointers must be valid and non-null (unless documented otherwise)
//! - Memory management follows Detour's rules (e.g., DT_TILE_FREE_DATA)
//! - NavMeshQuery is NOT thread-safe - use query pools for concurrent access
//!
//! ## Coordinate System
//!
//! **CRITICAL**: WoW and Detour use different coordinate systems!
//!
//! - WoW: X = North-South, Y = West-East, Z = Height (up)
//! - Detour: X = horizontal, Y = Height (up), Z = horizontal
//!
//! TrinityCore mmaps expect Detour coords as: `[WoW.Y, WoW.Z, WoW.X]`
//!
//! The `detour` safe wrapper crate handles this conversion automatically.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

// Include the generated bindings from build.rs
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// Status code constants (must match DetourStatus.h / wrapper.h)
pub const DT_SUCCESS: dtStatus = 1 << 30;
pub const DT_FAILURE: dtStatus = 1 << 31;
pub const DT_IN_PROGRESS: dtStatus = 1 << 29;

// Status detail masks
pub const DT_WRONG_MAGIC: dtStatus = 1 << 0;
pub const DT_WRONG_VERSION: dtStatus = 1 << 1;
pub const DT_OUT_OF_MEMORY: dtStatus = 1 << 2;
pub const DT_INVALID_PARAM: dtStatus = 1 << 3;
pub const DT_BUFFER_TOO_SMALL: dtStatus = 1 << 4;
pub const DT_OUT_OF_NODES: dtStatus = 1 << 5;
pub const DT_PARTIAL_RESULT: dtStatus = 1 << 6;

// Tile flags
pub const DT_TILE_FREE_DATA: i32 = 0x01;

// Max areas for query filter
pub const DT_MAX_AREAS: i32 = 64;

/// Check if a Detour status indicates success.
#[inline]
pub fn dt_status_succeed(status: dtStatus) -> bool {
    (status & DT_SUCCESS) != 0
}

/// Check if a Detour status indicates failure.
#[inline]
pub fn dt_status_failed(status: dtStatus) -> bool {
    (status & DT_FAILURE) != 0
}

/// Check if a Detour status indicates in-progress.
#[inline]
pub fn dt_status_in_progress(status: dtStatus) -> bool {
    (status & DT_IN_PROGRESS) != 0
}

/// Check if a Detour status has a specific detail flag.
#[inline]
pub fn dt_status_detail(status: dtStatus, detail: dtStatus) -> bool {
    (status & detail) != 0
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_status_flags() {
        assert!(dt_status_succeed(DT_SUCCESS));
        assert!(!dt_status_failed(DT_SUCCESS));

        assert!(dt_status_failed(DT_FAILURE));
        assert!(!dt_status_succeed(DT_FAILURE));

        // Combined status
        let partial = DT_SUCCESS | DT_PARTIAL_RESULT;
        assert!(dt_status_succeed(partial));
        assert!(dt_status_detail(partial, DT_PARTIAL_RESULT));
    }

    #[test]
    fn test_alloc_free_navmesh() {
        unsafe {
            let nav = wrapper_dtAllocNavMesh();
            assert!(!nav.is_null());
            wrapper_dtFreeNavMesh(nav);
        }
    }

    #[test]
    fn test_alloc_free_query() {
        unsafe {
            let query = wrapper_dtAllocNavMeshQuery();
            assert!(!query.is_null());
            wrapper_dtFreeNavMeshQuery(query);
        }
    }

    #[test]
    fn test_alloc_free_filter() {
        unsafe {
            let filter = wrapper_dtAllocQueryFilter();
            assert!(!filter.is_null());

            // Test default values
            let include = wrapper_dtQueryFilter_getIncludeFlags(filter);
            assert_eq!(include, 0xffff);

            let exclude = wrapper_dtQueryFilter_getExcludeFlags(filter);
            assert_eq!(exclude, 0);

            wrapper_dtFreeQueryFilter(filter);
        }
    }
}
