-- modules/questing/recorder.lua
-- Recording Mode — ADR 09a work unit W5, ADR 09 §11.1.
--
-- Retiring the RestedXP importer removes the only bulk source of route content (the retired corpus
-- was 107,399 actions across 277 profiles). This module is the replacement pipeline, not a
-- convenience: a human plays a zone once, the recorder watches the event bus, and the platform gets
-- a first-draft campaign the author repairs.
--
-- THE CENTRAL RULE: record Tasks, never waypoints. 100% of the importer's 38,726 Travel positions
-- carried world_z = 0 because guide text never had heights, and that single defect is what made the
-- corpus unusable. Movement is regenerated by NavServer at resolve time, so the recorder emits
-- intent (which quest, which npc, which item) and nothing about how the player got there. A player
-- position is stored only as incidental `context` on a task — it disambiguates WHICH spawn of npc
-- 823 was used, and is never a route.
--
-- `resolved` is deliberately absent from every node: it is derived server-side by sentinel-resolver
-- against a db_fingerprint the client does not have. A recording that claimed `resolved` would be
-- asserting a lowering it never performed.
--
-- Purity: this is a view-model over an event stream, exactly like runner_state.lua. It touches the
-- Sylvannas SDK in one place only (`save`), so the whole recording contract is exercisable offline
-- against a real EventBus.

local JSON = require("core/JSON")

local Recorder = {}
Recorder.__index = Recorder

Recorder.SCHEMA_VERSION = 3

-- The topics the recorder listens on. Only `player:profile_refreshed` has a producer today
-- (runtime/sensor_hub.lua) — the `game:*` quest/service topics are the observation surface this
-- unit defines and a later callback-bridge unit must publish. They are namespaced `game:` to match
-- callback_bridge.lua, which is where a real client signal would originate.
Recorder.TOPICS = {
    "game:quest_accepted",
    "game:quest_turned_in",
    "game:quest_abandoned",
    "game:quest_objective_progress",
    "game:vendor_used",
    "game:trainer_used",
    "game:taxi_taken",
    "game:hearthstone_used",
    "player:profile_refreshed",
}

-- ---------------------------------------------------------------------------
-- Identity
-- ---------------------------------------------------------------------------
-- Plan §1.1 specifies uuid v7. The sandbox has no uuid library and no monotonic source good enough
-- to make v7's timestamp field meaningful, so recordings mint v4-shaped ids: still a lowercase
-- hyphenated uuid string, still never reused, just not time-sortable. Sort order is carried by the
-- node list and its edges instead, which is what the graph actually reads.
local HEX = "0123456789abcdef"

-- A PRIVATE random stream, not `math.random`, for two reasons that both bite:
--   1. LuaJIT's global generator is unseeded, so every session would mint the SAME id sequence and
--      two recordings of two different zones would collide on ids §1.1 promises are never reused.
--   2. Seeding the global generator to fix (1) would silently change the draws every other module
--      and every other offline suite gets, which is a wide blast radius for an id helper.
-- A plain LCG is enough here: these ids need to be unique and opaque, not unguessable.
local rng_state = nil

local function next_draw(modulo)
    if not rng_state then
        local seconds = (core and core.time and core.time()) or 0
        if seconds == 0 and type(os) == "table" and os.time then
            seconds = os.time()
        end
        rng_state = (math.floor(seconds * 1000) % 2147483647) + 1
    end
    rng_state = (1103515245 * rng_state + 12345) % 2147483648
    -- Take middle bits: an LCG's low bits cycle with a very short period.
    return (math.floor(rng_state / 65536) % modulo) + 1
end

local function hex_digits(count)
    local out = {}
    for index = 1, count do
        local pick = next_draw(16)
        out[index] = HEX:sub(pick, pick)
    end
    return table.concat(out)
end

local function generate_uuid()
    -- One draw, used for both bounds: two independent draws produce a slice of the wrong length
    -- (or an empty one), which silently emits a malformed uuid nobody validates downstream.
    local variant_index = next_draw(4)
    local variant = ("89ab"):sub(variant_index, variant_index)
    return table.concat({
        hex_digits(8), "-",
        hex_digits(4), "-",
        "4" .. hex_digits(3), "-",
        variant .. hex_digits(3), "-",
        hex_digits(12),
    })
end

-- ---------------------------------------------------------------------------
-- Entity references (plan §1.2)
-- ---------------------------------------------------------------------------
-- `ref` is authoritative and `label` is a cached display string, captured from whatever the game
-- already handed us. The recorder never resolves a name over the network: a name lookup during play
-- is a stall the human would feel, and the resolver refreshes labels anyway.
local function entity_ref(kind, id, label)
    local numeric = tonumber(id)
    if not numeric then
        return nil
    end
    local ref = { ref = kind .. ":" .. string.format("%d", numeric) }
    if type(label) == "string" and label ~= "" then
        ref.label = label
    end
    return ref
end

local function first_number(...)
    for index = 1, select("#", ...) do
        local value = tonumber((select(index, ...)))
        if value then
            return value
        end
    end
    return nil
end

local function first_string(...)
    for index = 1, select("#", ...) do
        local value = select(index, ...)
        if type(value) == "string" and value ~= "" then
            return value
        end
    end
    return nil
end

-- ---------------------------------------------------------------------------
-- Construction
-- ---------------------------------------------------------------------------

--- @param opts table `{ event_bus, now, new_id }`. `now` and `new_id` are injectable so the whole
---        recorder is deterministic offline; in game they default to core.time() and a v4 uuid.
function Recorder:new(opts)
    opts = opts or {}
    local o = setmetatable({}, Recorder)
    o._event_bus = opts.event_bus
    o._now = opts.now or function()
        return (core and core.time and core.time()) or 0
    end
    o._new_id = opts.new_id or generate_uuid
    o._tokens = {}
    o._recording = false
    o._campaign = nil
    return o
end

-- ---------------------------------------------------------------------------
-- Control verbs
-- ---------------------------------------------------------------------------

--- Begin a recording. Any previous campaign is dropped — `get_campaign()` after a restart must not
--- silently blend two play sessions into one route.
function Recorder:start(name)
    if self._recording then
        self:stop()
    end

    local graph_id = self._new_id()
    self._campaign = {
        schema_version = Recorder.SCHEMA_VERSION,
        id = self._new_id(),
        name = name or "Recording",
        imports = {},
        variables = {},
        conditions = {},
        graphs = {
            {
                id = graph_id,
                name = name or "Recording",
                entry_node = nil,
                nodes = {},
                edges = {},
            },
        },
    }
    self._graph = self._campaign.graphs[1]
    self._open_objectives = {}
    self._accepted_quests = {}
    self._last_key = nil
    self._last_position = nil
    self._last_map_id = nil
    self._recording = true

    self:_subscribe()
    return self._campaign
end

--- Stop recording and return the campaign. The campaign stays readable after stop so the operator
--- can inspect and save it.
function Recorder:stop()
    self:_unsubscribe()
    self._recording = false
    return self._campaign
end

function Recorder:is_recording()
    return self._recording == true
end

function Recorder:get_campaign()
    return self._campaign
end

-- ---------------------------------------------------------------------------
-- Subscription
-- ---------------------------------------------------------------------------

function Recorder:_subscribe()
    if not self._event_bus then
        return
    end
    for _, topic in ipairs(Recorder.TOPICS) do
        local captured = topic
        local token = self._event_bus:subscribe(topic, function(payload)
            self:observe(captured, payload)
        end)
        self._tokens[#self._tokens + 1] = token
    end
end

function Recorder:_unsubscribe()
    if self._event_bus then
        for _, token in ipairs(self._tokens) do
            self._event_bus:unsubscribe(token)
        end
    end
    self._tokens = {}
end

--- Single entry point for every observation. Kept public so a suite can drive the recorder without
--- a bus at all, and so the bus handlers stay one line each.
function Recorder:observe(topic, payload)
    if not self._recording then
        return
    end
    payload = payload or {}

    if topic == "player:profile_refreshed" then
        self:_remember_position(payload)
    elseif topic == "game:quest_accepted" then
        self:_on_quest_accepted(payload)
    elseif topic == "game:quest_turned_in" then
        self:_on_quest_turned_in(payload)
    elseif topic == "game:quest_abandoned" then
        self:_on_quest_abandoned(payload)
    elseif topic == "game:quest_objective_progress" then
        self:_on_objective_progress(payload)
    elseif topic == "game:vendor_used" then
        self:_on_vendor_used(payload)
    elseif topic == "game:trainer_used" then
        self:_on_trainer_used(payload)
    elseif topic == "game:taxi_taken" then
        self:_on_taxi_taken(payload)
    elseif topic == "game:hearthstone_used" then
        self:_on_hearthstone_used(payload)
    end
end

-- ---------------------------------------------------------------------------
-- Position: context, never route
-- ---------------------------------------------------------------------------

--- The position firehose is absorbed here and goes no further. It is stamped onto the NEXT task as
--- context so the resolver can pick the right spawn of a multi-spawn npc; it never becomes a node,
--- an edge, or a waypoint list.
function Recorder:_remember_position(payload)
    local position = payload.position
    if type(position) == "table" and tonumber(position.x) and tonumber(position.y) then
        -- Copy, never alias: the SDK reuses position tables between frames, so a stored reference
        -- would mutate every task already recorded (the live-client finding behind
        -- "plain-copy every SDK position").
        self._last_position = {
            x = tonumber(position.x),
            y = tonumber(position.y),
            z = tonumber(position.z) or 0,
        }
    end
    local map_id = first_number(payload.map_id, payload.map, payload.instance_id)
    if map_id then
        self._last_map_id = map_id
    end
end

-- ---------------------------------------------------------------------------
-- Node emission
-- ---------------------------------------------------------------------------

--- Append a task. `dedup_key` collapses consecutive identical observations — a client that re-fires
--- the same accept, or a human spam-clicking one vendor, is one intent, not six.
--- @return table|nil the appended node, or nil when the observation was collapsed
function Recorder:_emit(node_type, intent, dedup_key)
    if dedup_key and self._last_key == dedup_key then
        return nil
    end

    local node = {
        id = self._new_id(),
        type = node_type,
        intent = intent,
        -- `context` is recording provenance, deliberately outside `intent`: intent is the authored
        -- source of truth the resolver lowers, context is only a hint for disambiguation and may be
        -- dropped without changing meaning.
        context = {
            recorded_at = self._now(),
        },
    }
    if self._last_position then
        node.context.position = {
            x = self._last_position.x,
            y = self._last_position.y,
            z = self._last_position.z,
        }
    end
    if self._last_map_id then
        node.context.map_id = self._last_map_id
    end

    self._graph.nodes[#self._graph.nodes + 1] = node
    self._last_key = dedup_key
    self:_rebuild_graph()
    return node
end

--- Recorded routes are strictly linear, so the edge chain and entry point are derived from the node
--- list rather than patched incrementally. That keeps retraction (abandon) correct for free: drop
--- nodes, rebuild, done — no dangling edge can survive.
function Recorder:_rebuild_graph()
    local nodes = self._graph.nodes
    local edges = {}
    for index = 1, #nodes - 1 do
        edges[index] = {
            id = self._new_id(),
            from = nodes[index].id,
            to = nodes[index + 1].id,
            -- `guard` is omitted rather than set: an unguarded edge is the default sequential
            -- advance, and branches are authored later in the IDE, never recorded.
        }
    end
    self._graph.edges = edges
    self._graph.entry_node = nodes[1] and nodes[1].id or nil
end

--- Drop every task belonging to `quest_id` and rebuild the chain.
function Recorder:_retract_quest(quest_id)
    local ref = "quest:" .. string.format("%d", quest_id)
    local kept = {}
    for _, node in ipairs(self._graph.nodes) do
        local quest = node.intent and node.intent.quest
        if not (quest and quest.ref == ref) then
            kept[#kept + 1] = node
        end
    end
    self._graph.nodes = kept
    self._last_key = nil
    self:_rebuild_graph()
end

-- ---------------------------------------------------------------------------
-- Handlers
-- ---------------------------------------------------------------------------

local function quest_ref_of(payload)
    return entity_ref("quest",
        first_number(payload.quest_id, payload.quest, payload.id),
        first_string(payload.quest_name, payload.title))
end

local function npc_ref_of(payload)
    return entity_ref("npc",
        first_number(payload.npc_id, payload.npc_entry, payload.entry),
        first_string(payload.npc_name, payload.name))
end

function Recorder:_on_quest_accepted(payload)
    local quest = quest_ref_of(payload)
    if not quest then
        return
    end
    -- A quest already in the recorded log is not new intent, even if the client re-announces it
    -- (QUEST_LOG_UPDATE fires far more often than a quest is actually taken).
    if self._accepted_quests[quest.ref] then
        return
    end
    self._accepted_quests[quest.ref] = true

    local intent = { quest = quest }
    intent.from = npc_ref_of(payload)
    self:_emit("questing.AcceptQuest", intent, "accept:" .. quest.ref)
end

function Recorder:_on_quest_turned_in(payload)
    local quest = quest_ref_of(payload)
    if not quest then
        return
    end
    local intent = { quest = quest }
    intent.to = npc_ref_of(payload)
    self:_emit("questing.TurnIn", intent, "turnin:" .. quest.ref)

    -- Close the quest's books: a repeatable quest taken again later is genuinely new intent, so its
    -- objectives must be allowed to open fresh tasks.
    self._accepted_quests[quest.ref] = nil
    self:_close_objectives(quest.ref)
end

function Recorder:_on_quest_abandoned(payload)
    local quest = quest_ref_of(payload)
    if not quest then
        return
    end
    -- The plan's task vocabulary (AcceptQuest TurnIn Kill Collect Vendor Trainer Flight Hearth Gate
    -- Travel) has no Abandon, and inventing one would emit a type sentinel-resolver cannot lower.
    -- An abandon is the human undoing intent, so the recorder retracts what that quest contributed
    -- rather than recording the undo as a step.
    self:_retract_quest(first_number(payload.quest_id, payload.quest, payload.id))
    self._accepted_quests[quest.ref] = nil
    self:_close_objectives(quest.ref)
end

function Recorder:_close_objectives(quest_ref)
    for key in pairs(self._open_objectives) do
        if key:sub(1, #quest_ref + 1) == quest_ref .. "#" then
            self._open_objectives[key] = nil
        end
    end
end

--- Objective progress is the one stream that MUST collapse: an objective ticking 1/10 -> 10/10 is a
--- single "kill ten of these" task. Collapse is keyed on the objective, not on adjacency, because
--- two objectives of one quest routinely advance together (a mob that both dies and drops) and a
--- consecutive-only rule would emit a node per alternation.
function Recorder:_on_objective_progress(payload)
    local quest = quest_ref_of(payload)
    if not quest then
        return
    end

    local kind = first_string(payload.kind, payload.objective_type) or ""
    kind = kind:lower()
    local item_id = first_number(payload.item_id, payload.item_entry)
    local target_id = first_number(payload.target_id, payload.npc_id, payload.creature_id)
    local is_collect = (kind == "collect" or kind == "item" or kind == "object")
        or (kind == "" and item_id ~= nil)

    local objective_key = quest.ref .. "#" .. tostring(
        payload.objective_index or payload.index or (is_collect and item_id) or target_id or "1")

    local have = first_number(payload.have, payload.current, payload.count) or 1
    local need = first_number(payload.need, payload.required, payload.total)

    local existing = self._open_objectives[objective_key]
    if existing then
        -- Same objective, more progress: raise the count in place. Never a second node.
        existing.intent.count = math.max(existing.intent.count or 0, need or have)
        return
    end

    local intent = { quest = quest, count = need or have }
    local node_type
    if is_collect then
        node_type = "questing.Collect"
        intent.item = entity_ref("item", item_id, first_string(payload.item_name, payload.objective_name))
        if not intent.item then
            intent.item = entity_ref("object", first_number(payload.object_id), first_string(payload.object_name))
        end
    else
        node_type = "questing.Kill"
        intent.target = entity_ref("npc", target_id, first_string(payload.target_name, payload.objective_name))
    end

    local node = self:_emit(node_type, intent, "objective:" .. objective_key)
    if node then
        self._open_objectives[objective_key] = node
    end
end

function Recorder:_on_vendor_used(payload)
    local npc = npc_ref_of(payload)
    if not npc then
        return
    end
    local intent = { npc = npc }
    if type(payload.actions) == "table" then
        local actions = {}
        for _, action in ipairs(payload.actions) do
            if type(action) == "string" then
                actions[#actions + 1] = action
            end
        end
        intent.actions = actions
    end
    self:_emit("questing.Vendor", intent, "vendor:" .. npc.ref)
end

function Recorder:_on_trainer_used(payload)
    local npc = npc_ref_of(payload)
    if not npc then
        return
    end
    self:_emit("questing.Trainer", { npc = npc }, "trainer:" .. npc.ref)
end

function Recorder:_on_taxi_taken(payload)
    local to = entity_ref("area",
        first_number(payload.to_area_id, payload.to_node, payload.to),
        first_string(payload.to_area_name, payload.to_name))
    if not to then
        return
    end
    local intent = { to = to }
    intent.from = entity_ref("area",
        first_number(payload.from_area_id, payload.from_node, payload.from),
        first_string(payload.from_area_name, payload.from_name))
    intent.npc = npc_ref_of(payload)
    self:_emit("questing.Flight", intent, "flight:" .. to.ref)
end

function Recorder:_on_hearthstone_used(payload)
    local destination = entity_ref("area",
        first_number(payload.area_id, payload.zone_id, payload.destination),
        first_string(payload.area_name, payload.zone_name, payload.destination_name))
    if not destination then
        return
    end
    self:_emit("questing.Hearth", { destination = destination }, "hearth:" .. destination.ref)
end

-- ---------------------------------------------------------------------------
-- Persistence
-- ---------------------------------------------------------------------------

--- Write the campaign through the sandbox file IO. Sylvannas' signature is
--- `core.write_data_file(filename, data)` with NO self, and the loader requires the file to exist
--- before it can be written — both learned the hard way in runtime_profile.lua, where passing
--- `core` as the first argument made every save fail silently.
function Recorder:save(path)
    if not self._campaign or type(path) ~= "string" or path == "" then
        return false
    end

    local encoded, err = JSON.encode(self._campaign, true)
    if not encoded or encoded == "" or err then
        return false
    end

    if not (core and core.write_data_file) then
        return false
    end
    if core.create_data_file then
        pcall(core.create_data_file, path)
    end
    local ok = pcall(core.write_data_file, path, encoded)
    return ok == true
end

return Recorder
