//! Operation — Volume 7 §3 Revised Operation Structure (supersedes Volume 5)
//! 
//! See: docs/adr/007-operations.md

use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::enums::{OptimizationPolicy, CompletionMetrics, OperationAnalytics};
use crate::condition::{Condition, ExitConditions, OperationGoal, OperationDependency};
use crate::action::Action;
use crate::variable::Variable;

/// Operation — Volume 7 §3 Revised Operation Structure
/// 
/// Self-contained authoring/execution unit with goals, entry/exit conditions,
/// dependencies, optimization policy, and analytics.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Operation {
    pub id: Uuid,
    pub name: String,
    pub description: String,
    pub enabled: bool,
    pub level_range: crate::metadata::LevelRange,
    pub priority: u32,
    pub tags: Vec<String>,
    
    // Volume 7 additions
    pub goals: Vec<OperationGoal>,
    pub entry_conditions: Vec<Condition>,
    pub exit_conditions: ExitConditions,
    pub dependencies: Vec<OperationDependency>,
    pub optimization_policy: OptimizationPolicy,
    pub completion_metrics: CompletionMetrics,
    pub sub_operations: Vec<Uuid>,
    pub analytics: OperationAnalytics,

    /// Provenance tag — set when this Operation was generated by expanding a
    /// Blueprint during compilation (Volume 6 §25). `None` for hand-authored
    /// Operations.
    #[serde(default)]
    pub generated_from: Option<Uuid>,
    
    // Base fields (from Volume 5)
    pub variables: Vec<Variable>,
    pub actions: Vec<Action>,
}

impl Operation {
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            id: Uuid::new_v4(),
            name: name.into(),
            description: String::new(),
            enabled: true,
            level_range: crate::metadata::LevelRange::default(),
            priority: 100,
            tags: Vec::new(),
            goals: Vec::new(),
            entry_conditions: Vec::new(),
            exit_conditions: ExitConditions::new(),
            dependencies: Vec::new(),
            optimization_policy: OptimizationPolicy::default(),
            completion_metrics: CompletionMetrics::default(),
            sub_operations: Vec::new(),
            analytics: OperationAnalytics::default(),
            generated_from: None,
            variables: Vec::new(),
            actions: Vec::new(),
        }
    }
    
    pub fn with_description(mut self, desc: impl Into<String>) -> Self {
        self.description = desc.into();
        self
    }
    
    pub fn with_level_range(mut self, min: u8, max: u8) -> Self {
        self.level_range = crate::metadata::LevelRange::new(min, max);
        self
    }
    
    pub fn with_priority(mut self, priority: u32) -> Self {
        self.priority = priority;
        self
    }
    
    pub fn with_goals(mut self, goals: Vec<OperationGoal>) -> Self {
        self.goals = goals;
        self
    }
    
    pub fn with_entry_conditions(mut self, conditions: Vec<Condition>) -> Self {
        self.entry_conditions = conditions;
        self
    }
    
    pub fn with_exit_conditions(mut self, exit: ExitConditions) -> Self {
        self.exit_conditions = exit;
        self
    }
    
    pub fn with_dependency(mut self, dep: OperationDependency) -> Self {
        self.dependencies.push(dep);
        self
    }
    
    pub fn with_optimization_policy(mut self, policy: OptimizationPolicy) -> Self {
        self.optimization_policy = policy;
        self
    }
    
    pub fn with_actions(mut self, actions: Vec<Action>) -> Self {
        self.actions = actions;
        self
    }
}