[package]
name = "sentinel-compiler"
description = "Compiles Sentinel Projects into Runtime Profiles (Phase 6)."
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sentinel-models = { path = "../shared" }
uuid = { workspace = true }
thiserror = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
sentinel-importer = { path = "../importer" }
sentinel-queryclient = { path = "../queryclient" }
tokio = { workspace = true }
serde_json = { workspace = true }