-- kernel/catalogs/taxi_paths.lua
-- GENERATED by sentinel/tools/regen_taxi_paths_catalog.py from TaxiPath.dbc (2.4.3).
-- Do not hand-edit; regenerate. taxi_paths.json is the same edge list for the Rust
-- resolver and is written by the same run -- patching one alone splits the platform.
--
-- `edges` is an ADJACENCY index, edges[from_node][to_node] = { path, cost }, so asking
-- "is there a flight A -> B" is two table lookups no matter how large the catalog is.
-- A flat row list would make every Flight validation a 514-row scan, and the compiler
-- validates every step of every guide.
--
-- These are DIRECT hops only. TaxiPath.dbc has no notion of a connecting flight;
-- chaining hops is the caller's decision and is deliberately not baked in here.
--
-- 26 of the DBC's 514 rows are EXCLUDED: their endpoint is a node taxi_nodes.lua
-- refused as usable by neither faction (boat/zeppelin pseudo-nodes, quest-scripted
-- cinematic flights, dev land). TaxiNodes.resolve can never name those ids, so an
-- edge reaching one could only ever answer "connected" about a hop no flight master
-- sells. The full excluded list, with reasons, is in taxi_paths.json.
local M = {}

M.edges = {
    [2] = {
        [4] = { path = 6, cost = 110 },
        [5] = { path = 9, cost = 210 },
        [6] = { path = 13, cost = 50 },
        [12] = { path = 23, cost = 330 },
        [19] = { path = 40, cost = 630 },
        [45] = { path = 245, cost = 830 },
        [71] = { path = 427, cost = 830 },
        [74] = { path = 681, cost = 730 },
        [195] = { path = 753, cost = 630 },
    },
    [4] = {
        [2] = { path = 7, cost = 110 },
        [5] = { path = 249, cost = 210 },
        [12] = { path = 250, cost = 330 },
        [19] = { path = 255, cost = 630 },
        [195] = { path = 749, cost = 630 },
    },
    [5] = {
        [2] = { path = 8, cost = 210 },
        [4] = { path = 254, cost = 110 },
        [12] = { path = 257, cost = 330 },
        [71] = { path = 469, cost = 830 },
    },
    [6] = {
        [2] = { path = 12, cost = 50 },
        [7] = { path = 18, cost = 330 },
        [8] = { path = 16, cost = 110 },
        [14] = { path = 27, cost = 330 },
        [16] = { path = 31, cost = 530 },
        [43] = { path = 263, cost = 730 },
        [59] = { path = 314, cost = 1020 },
        [66] = { path = 428, cost = 1020 },
        [67] = { path = 438, cost = 1020 },
        [74] = { path = 404, cost = 830 },
        [213] = { path = 807, cost = 2775 },
    },
    [7] = {
        [6] = { path = 17, cost = 330 },
        [8] = { path = 266, cost = 110 },
        [14] = { path = 271, cost = 330 },
        [16] = { path = 269, cost = 530 },
    },
    [8] = {
        [6] = { path = 15, cost = 110 },
        [7] = { path = 265, cost = 330 },
        [16] = { path = 267, cost = 530 },
        [74] = { path = 526, cost = 830 },
    },
    [10] = {
        [11] = { path = 21, cost = 110 },
        [13] = { path = 440, cost = 330 },
    },
    [11] = {
        [10] = { path = 20, cost = 110 },
        [13] = { path = 25, cost = 330 },
        [17] = { path = 33, cost = 530 },
        [21] = { path = 39, cost = 630 },
        [60] = { path = 383, cost = 1020 },
        [68] = { path = 357, cost = 1020 },
        [76] = { path = 414, cost = 730 },
    },
    [12] = {
        [2] = { path = 22, cost = 330 },
        [4] = { path = 252, cost = 110 },
        [5] = { path = 258, cost = 210 },
        [19] = { path = 259, cost = 630 },
        [45] = { path = 261, cost = 830 },
        [195] = { path = 751, cost = 630 },
    },
    [13] = {
        [10] = { path = 441, cost = 110 },
        [11] = { path = 24, cost = 330 },
        [17] = { path = 322, cost = 530 },
        [76] = { path = 413, cost = 730 },
    },
    [14] = {
        [6] = { path = 26, cost = 330 },
        [7] = { path = 272, cost = 330 },
        [16] = { path = 274, cost = 530 },
        [43] = { path = 230, cost = 730 },
        [66] = { path = 347, cost = 830 },
    },
    [16] = {
        [6] = { path = 30, cost = 530 },
        [7] = { path = 270, cost = 330 },
        [8] = { path = 268, cost = 110 },
        [14] = { path = 273, cost = 330 },
        [43] = { path = 275, cost = 730 },
    },
    [17] = {
        [11] = { path = 32, cost = 530 },
        [13] = { path = 321, cost = 330 },
        [21] = { path = 320, cost = 630 },
        [76] = { path = 484, cost = 730 },
    },
    [18] = {
        [20] = { path = 35, cost = 630 },
        [21] = { path = 36, cost = 630 },
        [56] = { path = 82, cost = 630 },
    },
    [19] = {
        [2] = { path = 41, cost = 630 },
        [4] = { path = 256, cost = 530 },
        [12] = { path = 260, cost = 330 },
        [195] = { path = 747, cost = 630 },
    },
    [20] = {
        [18] = { path = 34, cost = 630 },
        [21] = { path = 361, cost = 630 },
        [56] = { path = 344, cost = 630 },
        [70] = { path = 682, cost = 830 },
    },
    [21] = {
        [11] = { path = 38, cost = 630 },
        [17] = { path = 319, cost = 630 },
        [18] = { path = 37, cost = 630 },
        [20] = { path = 362, cost = 530 },
        [56] = { path = 317, cost = 710 },
        [70] = { path = 378, cost = 830 },
        [75] = { path = 406, cost = 830 },
    },
    [22] = {
        [23] = { path = 387, cost = 50 },
        [25] = { path = 46, cost = 110 },
        [29] = { path = 53, cost = 210 },
        [30] = { path = 55, cost = 430 },
        [38] = { path = 162, cost = 530 },
        [40] = { path = 309, cost = 730 },
        [42] = { path = 228, cost = 730 },
        [44] = { path = 290, cost = 830 },
        [55] = { path = 345, cost = 630 },
        [58] = { path = 702, cost = 530 },
        [77] = { path = 419, cost = 110 },
    },
    [23] = {
        [22] = { path = 42, cost = 50 },
        [25] = { path = 47, cost = 110 },
        [40] = { path = 224, cost = 730 },
        [44] = { path = 243, cost = 830 },
        [48] = { path = 338, cost = 830 },
        [53] = { path = 399, cost = 1020 },
        [55] = { path = 335, cost = 630 },
        [61] = { path = 328, cost = 530 },
        [80] = { path = 790, cost = 110 },
        [198] = { path = 758, cost = 1 },
    },
    [25] = {
        [22] = { path = 44, cost = 110 },
        [23] = { path = 45, cost = 110 },
        [29] = { path = 279, cost = 210 },
        [30] = { path = 281, cost = 430 },
        [40] = { path = 393, cost = 730 },
        [42] = { path = 355, cost = 730 },
        [44] = { path = 283, cost = 830 },
        [48] = { path = 287, cost = 930 },
        [55] = { path = 360, cost = 630 },
        [58] = { path = 354, cost = 330 },
        [61] = { path = 334, cost = 530 },
        [77] = { path = 417, cost = 110 },
        [80] = { path = 462, cost = 110 },
    },
    [26] = {
        [27] = { path = 101, cost = 0 },
        [28] = { path = 51, cost = 330 },
        [32] = { path = 181, cost = 630 },
        [33] = { path = 59, cost = 330 },
        [37] = { path = 385, cost = 530 },
        [41] = { path = 226, cost = 730 },
        [49] = { path = 289, cost = 830 },
        [64] = { path = 330, cost = 730 },
        [65] = { path = 386, cost = 730 },
    },
    [27] = {
        [26] = { path = 102, cost = 0 },
    },
    [28] = {
        [26] = { path = 50, cost = 330 },
        [32] = { path = 660, cost = 730 },
        [33] = { path = 443, cost = 330 },
        [64] = { path = 467, cost = 730 },
        [80] = { path = 699, cost = 110 },
        [166] = { path = 668, cost = 830 },
        [167] = { path = 677, cost = 330 },
    },
    [29] = {
        [22] = { path = 52, cost = 210 },
        [25] = { path = 280, cost = 210 },
        [38] = { path = 358, cost = 530 },
        [58] = { path = 529, cost = 330 },
    },
    [30] = {
        [22] = { path = 54, cost = 430 },
        [25] = { path = 282, cost = 430 },
        [40] = { path = 308, cost = 730 },
        [42] = { path = 487, cost = 730 },
        [55] = { path = 695, cost = 630 },
        [77] = { path = 422, cost = 430 },
        [179] = { path = 719, cost = 630 },
    },
    [31] = {
        [32] = { path = 57, cost = 730 },
        [39] = { path = 324, cost = 730 },
        [41] = { path = 325, cost = 630 },
        [179] = { path = 721, cost = 630 },
    },
    [32] = {
        [26] = { path = 182, cost = 630 },
        [28] = { path = 661, cost = 730 },
        [31] = { path = 56, cost = 430 },
        [37] = { path = 163, cost = 530 },
        [39] = { path = 222, cost = 730 },
        [64] = { path = 445, cost = 730 },
        [80] = { path = 464, cost = 110 },
        [179] = { path = 717, cost = 630 },
    },
    [33] = {
        [26] = { path = 58, cost = 330 },
        [28] = { path = 444, cost = 330 },
        [37] = { path = 478, cost = 530 },
    },
    [37] = {
        [26] = { path = 384, cost = 530 },
        [32] = { path = 141, cost = 530 },
        [33] = { path = 477, cost = 330 },
        [41] = { path = 373, cost = 730 },
    },
    [38] = {
        [22] = { path = 161, cost = 530 },
        [29] = { path = 356, cost = 210 },
        [42] = { path = 376, cost = 730 },
    },
    [39] = {
        [31] = { path = 323, cost = 430 },
        [32] = { path = 201, cost = 630 },
        [73] = { path = 394, cost = 1020 },
        [79] = { path = 458, cost = 830 },
        [80] = { path = 688, cost = 110 },
    },
    [40] = {
        [22] = { path = 311, cost = 730 },
        [23] = { path = 223, cost = 730 },
        [25] = { path = 392, cost = 730 },
        [30] = { path = 310, cost = 430 },
        [42] = { path = 389, cost = 630 },
        [55] = { path = 388, cost = 630 },
        [72] = { path = 395, cost = 1020 },
        [79] = { path = 459, cost = 830 },
        [80] = { path = 689, cost = 110 },
    },
    [41] = {
        [26] = { path = 225, cost = 730 },
        [31] = { path = 326, cost = 430 },
        [37] = { path = 374, cost = 730 },
        [73] = { path = 471, cost = 1030 },
    },
    [42] = {
        [22] = { path = 227, cost = 730 },
        [25] = { path = 353, cost = 730 },
        [30] = { path = 486, cost = 430 },
        [38] = { path = 375, cost = 730 },
        [40] = { path = 391, cost = 630 },
        [72] = { path = 450, cost = 1030 },
    },
    [43] = {
        [6] = { path = 264, cost = 730 },
        [14] = { path = 229, cost = 330 },
        [16] = { path = 276, cost = 530 },
        [66] = { path = 475, cost = 1020 },
        [67] = { path = 349, cost = 1020 },
    },
    [44] = {
        [22] = { path = 291, cost = 830 },
        [23] = { path = 242, cost = 830 },
        [25] = { path = 284, cost = 830 },
        [48] = { path = 400, cost = 930 },
        [53] = { path = 500, cost = 1020 },
        [61] = { path = 482, cost = 530 },
    },
    [45] = {
        [2] = { path = 244, cost = 830 },
        [12] = { path = 262, cost = 330 },
        [71] = { path = 382, cost = 830 },
    },
    [48] = {
        [23] = { path = 341, cost = 930 },
        [25] = { path = 286, cost = 930 },
        [44] = { path = 401, cost = 830 },
        [53] = { path = 307, cost = 1020 },
        [58] = { path = 528, cost = 330 },
        [69] = { path = 365, cost = 830 },
        [166] = { path = 665, cost = 830 },
    },
    [49] = {
        [26] = { path = 368, cost = 830 },
        [52] = { path = 367, cost = 1020 },
        [65] = { path = 479, cost = 730 },
    },
    [52] = {
        [49] = { path = 298, cost = 830 },
        [64] = { path = 448, cost = 730 },
        [65] = { path = 339, cost = 730 },
    },
    [53] = {
        [23] = { path = 398, cost = 1020 },
        [44] = { path = 499, cost = 830 },
        [48] = { path = 306, cost = 930 },
        [69] = { path = 363, cost = 830 },
    },
    [55] = {
        [22] = { path = 348, cost = 630 },
        [23] = { path = 336, cost = 630 },
        [25] = { path = 304, cost = 110 },
        [30] = { path = 694, cost = 630 },
        [40] = { path = 390, cost = 730 },
        [77] = { path = 692, cost = 110 },
        [80] = { path = 697, cost = 110 },
        [179] = { path = 716, cost = 630 },
    },
    [56] = {
        [18] = { path = 121, cost = 630 },
        [20] = { path = 343, cost = 630 },
        [21] = { path = 318, cost = 630 },
        [70] = { path = 380, cost = 830 },
    },
    [58] = {
        [22] = { path = 703, cost = 110 },
        [25] = { path = 305, cost = 110 },
        [29] = { path = 530, cost = 210 },
        [48] = { path = 527, cost = 830 },
        [61] = { path = 350, cost = 530 },
        [166] = { path = 673, cost = 830 },
    },
    [59] = {
        [6] = { path = 312, cost = 0 },
    },
    [60] = {
        [11] = { path = 313, cost = 0 },
    },
    [61] = {
        [23] = { path = 327, cost = 530 },
        [25] = { path = 333, cost = 530 },
        [44] = { path = 481, cost = 830 },
        [58] = { path = 351, cost = 330 },
        [166] = { path = 670, cost = 830 },
    },
    [62] = {
        [27] = { path = 315, cost = 0 },
    },
    [63] = {
        [22] = { path = 316, cost = 0 },
    },
    [64] = {
        [26] = { path = 329, cost = 730 },
        [28] = { path = 468, cost = 330 },
        [32] = { path = 446, cost = 630 },
        [52] = { path = 447, cost = 1030 },
        [65] = { path = 332, cost = 730 },
        [80] = { path = 465, cost = 110 },
        [167] = { path = 678, cost = 330 },
    },
    [65] = {
        [26] = { path = 369, cost = 730 },
        [49] = { path = 480, cost = 1020 },
        [52] = { path = 371, cost = 1020 },
        [64] = { path = 372, cost = 730 },
        [166] = { path = 666, cost = 830 },
    },
    [66] = {
        [6] = { path = 429, cost = 1020 },
        [14] = { path = 346, cost = 330 },
        [43] = { path = 476, cost = 730 },
        [67] = { path = 431, cost = 1020 },
    },
    [67] = {
        [6] = { path = 437, cost = 1020 },
        [43] = { path = 352, cost = 730 },
        [66] = { path = 432, cost = 1020 },
        [205] = { path = 775, cost = 1020 },
        [213] = { path = 796, cost = 1750 },
    },
    [68] = {
        [11] = { path = 359, cost = 1020 },
        [76] = { path = 474, cost = 730 },
        [83] = { path = 766, cost = 1020 },
        [205] = { path = 771, cost = 1020 },
    },
    [69] = {
        [48] = { path = 364, cost = 930 },
        [53] = { path = 366, cost = 1020 },
    },
    [70] = {
        [20] = { path = 683, cost = 630 },
        [21] = { path = 377, cost = 830 },
        [56] = { path = 379, cost = 830 },
        [75] = { path = 408, cost = 830 },
    },
    [71] = {
        [2] = { path = 425, cost = 830 },
        [5] = { path = 470, cost = 210 },
        [45] = { path = 381, cost = 830 },
        [74] = { path = 410, cost = 830 },
    },
    [72] = {
        [40] = { path = 423, cost = 730 },
        [42] = { path = 449, cost = 730 },
        [79] = { path = 456, cost = 830 },
    },
    [73] = {
        [39] = { path = 424, cost = 730 },
        [41] = { path = 451, cost = 730 },
        [79] = { path = 457, cost = 830 },
    },
    [74] = {
        [2] = { path = 680, cost = 830 },
        [6] = { path = 402, cost = 830 },
        [8] = { path = 525, cost = 110 },
        [71] = { path = 411, cost = 830 },
    },
    [75] = {
        [21] = { path = 407, cost = 630 },
        [70] = { path = 409, cost = 830 },
    },
    [76] = {
        [11] = { path = 415, cost = 730 },
        [13] = { path = 412, cost = 330 },
        [17] = { path = 485, cost = 530 },
        [68] = { path = 473, cost = 1030 },
    },
    [77] = {
        [22] = { path = 420, cost = 110 },
        [25] = { path = 416, cost = 110 },
        [30] = { path = 421, cost = 430 },
        [55] = { path = 693, cost = 630 },
    },
    [79] = {
        [39] = { path = 452, cost = 730 },
        [40] = { path = 453, cost = 730 },
        [72] = { path = 454, cost = 1030 },
        [73] = { path = 455, cost = 1030 },
    },
    [80] = {
        [23] = { path = 791, cost = 110 },
        [25] = { path = 461, cost = 110 },
        [28] = { path = 698, cost = 330 },
        [32] = { path = 460, cost = 630 },
        [39] = { path = 690, cost = 730 },
        [40] = { path = 691, cost = 730 },
        [55] = { path = 696, cost = 630 },
        [64] = { path = 466, cost = 730 },
    },
    [82] = {
        [83] = { path = 489, cost = 330 },
        [213] = { path = 781, cost = 530 },
    },
    [83] = {
        [68] = { path = 767, cost = 1020 },
        [82] = { path = 488, cost = 110 },
        [205] = { path = 773, cost = 530 },
    },
    [84] = {
        [85] = { path = 494, cost = 0 },
        [86] = { path = 495, cost = 0 },
        [87] = { path = 496, cost = 0 },
    },
    [93] = {
        [94] = { path = 507, cost = 110 },
    },
    [94] = {
        [93] = { path = 508, cost = 110 },
    },
    [99] = {
        [102] = { path = 518, cost = 1020 },
        [127] = { path = 575, cost = 1020 },
        [130] = { path = 567, cost = 0 },
        [141] = { path = 602, cost = 1020 },
    },
    [100] = {
        [101] = { path = 516, cost = 1020 },
        [121] = { path = 558, cost = 1020 },
        [128] = { path = 686, cost = 1020 },
        [129] = { path = 566, cost = 0 },
        [149] = { path = 614, cost = 0 },
    },
    [101] = {
        [100] = { path = 515, cost = 1020 },
        [117] = { path = 536, cost = 1020 },
    },
    [102] = {
        [99] = { path = 517, cost = 1020 },
        [118] = { path = 538, cost = 1020 },
        [120] = { path = 544, cost = 1020 },
        [128] = { path = 573, cost = 1020 },
        [151] = { path = 619, cost = 1020 },
    },
    [103] = {
        [104] = { path = 520, cost = 0 },
    },
    [105] = {
        [106] = { path = 523, cost = 0 },
    },
    [107] = {
        [108] = { path = 522, cost = 0 },
    },
    [109] = {
        [110] = { path = 524, cost = 0 },
    },
    [111] = {
        [112] = { path = 531, cost = 0 },
    },
    [117] = {
        [101] = { path = 535, cost = 1020 },
        [119] = { path = 540, cost = 1020 },
        [125] = { path = 603, cost = 1020 },
        [128] = { path = 561, cost = 1020 },
        [156] = { path = 708, cost = 1020 },
        [164] = { path = 656, cost = 1020 },
    },
    [118] = {
        [102] = { path = 537, cost = 1020 },
        [120] = { path = 542, cost = 1020 },
        [126] = { path = 579, cost = 1020 },
        [128] = { path = 577, cost = 1020 },
        [151] = { path = 621, cost = 1020 },
    },
    [119] = {
        [117] = { path = 539, cost = 1020 },
        [121] = { path = 546, cost = 1020 },
        [128] = { path = 559, cost = 1020 },
    },
    [120] = {
        [102] = { path = 543, cost = 1020 },
        [118] = { path = 541, cost = 1020 },
        [128] = { path = 571, cost = 1020 },
    },
    [121] = {
        [100] = { path = 547, cost = 1020 },
        [119] = { path = 545, cost = 1020 },
        [124] = { path = 553, cost = 1020 },
        [128] = { path = 555, cost = 1020 },
    },
    [122] = {
        [125] = { path = 568, cost = 1020 },
        [126] = { path = 580, cost = 1020 },
        [139] = { path = 633, cost = 1020 },
        [150] = { path = 617, cost = 1020 },
        [156] = { path = 642, cost = 1020 },
        [160] = { path = 648, cost = 710 },
        [163] = { path = 653, cost = 1020 },
    },
    [123] = {
        [127] = { path = 551, cost = 1020 },
        [140] = { path = 594, cost = 875 },
        [159] = { path = 639, cost = 875 },
    },
    [124] = {
        [121] = { path = 554, cost = 1020 },
        [140] = { path = 598, cost = 875 },
        [159] = { path = 640, cost = 875 },
    },
    [125] = {
        [117] = { path = 570, cost = 1020 },
        [122] = { path = 569, cost = 1020 },
        [139] = { path = 593, cost = 1020 },
        [156] = { path = 631, cost = 510 },
        [160] = { path = 645, cost = 510 },
        [164] = { path = 658, cost = 1020 },
    },
    [126] = {
        [118] = { path = 578, cost = 1020 },
        [122] = { path = 581, cost = 1020 },
        [139] = { path = 592, cost = 1020 },
        [151] = { path = 624, cost = 1020 },
        [160] = { path = 646, cost = 510 },
        [163] = { path = 652, cost = 1020 },
    },
    [127] = {
        [99] = { path = 548, cost = 1020 },
        [123] = { path = 550, cost = 1020 },
        [128] = { path = 549, cost = 1020 },
    },
    [128] = {
        [100] = { path = 687, cost = 1020 },
        [102] = { path = 574, cost = 1020 },
        [117] = { path = 562, cost = 1020 },
        [118] = { path = 576, cost = 1020 },
        [119] = { path = 560, cost = 1020 },
        [120] = { path = 572, cost = 1020 },
        [121] = { path = 557, cost = 1020 },
        [127] = { path = 552, cost = 1020 },
        [151] = { path = 623, cost = 1020 },
    },
    [129] = {
        [100] = { path = 564, cost = 0 },
        [101] = { path = 582, cost = 0 },
        [149] = { path = 613, cost = 0 },
    },
    [130] = {
        [99] = { path = 565, cost = 0 },
        [102] = { path = 583, cost = 0 },
    },
    [131] = {
        [132] = { path = 584, cost = 0 },
    },
    [133] = {
        [134] = { path = 585, cost = 0 },
        [149] = { path = 612, cost = 0 },
    },
    [135] = {
        [136] = { path = 587, cost = 0 },
    },
    [137] = {
        [138] = { path = 589, cost = 0 },
    },
    [139] = {
        [122] = { path = 634, cost = 1020 },
        [125] = { path = 600, cost = 1020 },
        [126] = { path = 590, cost = 1020 },
        [150] = { path = 638, cost = 1020 },
    },
    [140] = {
        [123] = { path = 591, cost = 1020 },
        [124] = { path = 595, cost = 875 },
    },
    [141] = {
        [99] = { path = 601, cost = 1020 },
    },
    [142] = {
        [141] = { path = 604, cost = 1020 },
    },
    [144] = {
        [143] = { path = 605, cost = 0 },
    },
    [147] = {
        [148] = { path = 608, cost = 0 },
    },
    [148] = {
        [147] = { path = 607, cost = 0 },
    },
    [149] = {
        [100] = { path = 615, cost = 0 },
        [129] = { path = 611, cost = 0 },
    },
    [150] = {
        [122] = { path = 616, cost = 1020 },
        [139] = { path = 637, cost = 1020 },
    },
    [151] = {
        [102] = { path = 618, cost = 1020 },
        [118] = { path = 620, cost = 1020 },
        [126] = { path = 625, cost = 1020 },
        [128] = { path = 622, cost = 1020 },
        [163] = { path = 723, cost = 1020 },
    },
    [152] = {
        [153] = { path = 627, cost = 0 },
    },
    [156] = {
        [117] = { path = 709, cost = 1020 },
        [122] = { path = 641, cost = 1020 },
        [125] = { path = 630, cost = 510 },
        [160] = { path = 685, cost = 510 },
    },
    [159] = {
        [123] = { path = 636, cost = 875 },
        [124] = { path = 635, cost = 875 },
    },
    [160] = {
        [122] = { path = 647, cost = 710 },
        [125] = { path = 644, cost = 510 },
        [126] = { path = 643, cost = 510 },
        [156] = { path = 679, cost = 510 },
    },
    [163] = {
        [122] = { path = 650, cost = 1020 },
        [126] = { path = 654, cost = 1020 },
        [151] = { path = 722, cost = 1020 },
    },
    [164] = {
        [117] = { path = 655, cost = 1020 },
        [125] = { path = 657, cost = 1020 },
    },
    [166] = {
        [28] = { path = 669, cost = 530 },
        [48] = { path = 662, cost = 830 },
        [58] = { path = 672, cost = 530 },
        [61] = { path = 663, cost = 530 },
        [65] = { path = 664, cost = 830 },
        [167] = { path = 676, cost = 330 },
    },
    [167] = {
        [28] = { path = 671, cost = 330 },
        [64] = { path = 674, cost = 730 },
        [166] = { path = 675, cost = 830 },
    },
    [169] = {
        [170] = { path = 704, cost = 0 },
    },
    [171] = {
        [172] = { path = 705, cost = 0 },
    },
    [172] = {
        [171] = { path = 706, cost = 0 },
    },
    [179] = {
        [30] = { path = 718, cost = 430 },
        [31] = { path = 720, cost = 430 },
        [32] = { path = 715, cost = 630 },
        [55] = { path = 714, cost = 630 },
    },
    [180] = {
        [181] = { path = 724, cost = 0 },
    },
    [195] = {
        [2] = { path = 752, cost = 630 },
        [4] = { path = 748, cost = 110 },
        [12] = { path = 750, cost = 330 },
        [19] = { path = 746, cost = 630 },
    },
    [198] = {
        [23] = { path = 759, cost = 1 },
    },
    [205] = {
        [67] = { path = 776, cost = 1020 },
        [68] = { path = 772, cost = 1020 },
        [83] = { path = 774, cost = 530 },
        [213] = { path = 786, cost = 730 },
    },
    [209] = {
        [210] = { path = 779, cost = 0 },
    },
    [211] = {
        [212] = { path = 784, cost = 0 },
    },
    [212] = {
        [211] = { path = 788, cost = 0 },
    },
    [213] = {
        [67] = { path = 797, cost = 1750 },
        [82] = { path = 782, cost = 530 },
        [205] = { path = 787, cost = 730 },
    },
}

--- How many DBC rows the exclusion rule dropped. Pinned by the tests: if this moves,
--- the meaning of "a flyable route" changed and every Flight plan is affected.
M.excluded_edge_count = 26

---The fare and TaxiPath id for a direct flight, or nothing.
---
---Returns nil rather than raising for an unknown source: a Flight task validating a destination
---the character cannot reach is an ordinary answer, not a defect, and the caller must be able to
---ask about any pair of node ids without pre-checking that the source flies anywhere at all.
---@param from number|nil source node id
---@param to number|nil destination node id
---@return number|nil path_id, number|string|nil cost_or_err cost in copper, or "no_route"
function M.route(from, to)
    if type(from) ~= "number" or type(to) ~= "number" then return nil, "no_route" end
    local dests = M.edges[from]
    if not dests then return nil, "no_route" end
    local edge = dests[to]
    if not edge then return nil, "no_route" end
    return edge.path, edge.cost
end

---@param from number|nil source node id
---@param to number|nil destination node id
---@return boolean always a boolean, never nil, so it reads directly in a condition
function M.has_route(from, to)
    return M.route(from, to) ~= nil
end

---Every node reachable in one hop from `from`, as a { [to_node] = { path, cost } } table.
---Empty rather than nil for an unknown source, so callers can iterate without a guard.
---@param from number|nil source node id
---@return table
function M.destinations(from)
    if type(from) ~= "number" then return {} end
    return M.edges[from] or {}
end

return M
