local Keys = {
    SYSTEM_NOW_MS = "system.now_ms",
    SYSTEM_DELTA_MS = "system.delta_ms",
    SYSTEM_PING_MS = "system.ping_ms",
    SYSTEM_MAP_ID = "system.map_id",
    SYSTEM_MAP_NAME = "system.map_name",
    PLAYER_OBJECT = "player.object",
    PLAYER_TARGET = "player.target",
    PLAYER_POSITION = "player.position",
    PLAYER_HEALTH_PCT = "player.health_pct",
    PLAYER_MANA_PCT = "player.mana_pct",
    PLAYER_IS_CASTING = "player.is_casting",
    PLAYER_IS_CHANNELING = "player.is_channeling",
    PLAYER_IS_MOVING = "player.is_moving",
    PLAYER_IS_AUTO_ATTACKING = "player.is_auto_attacking",
    PLAYER_ATTACK_SPEED_S = "player.attack_speed_s",
    COMBAT_STATE = "combat.state",
    COMBAT_TARGET = "combat.target",
    COMBAT_GCD_UNTIL_MS = "combat.gcd_until_ms",
    NAV_STATE = "nav.state",
    MODULE_COMBAT_ENABLED = "module.combat.enabled",
    MODULE_COMBAT_TARGET_DUMMY = "module.combat.target_dummy",
}

return Keys
