-- tests/fixtures/spell_chain_tbc243.lua
-- GENERATED by sentinel/tools/regen_catalog_chain_fixture.py -- DO NOT HAND-EDIT.
--
-- The rank progression of every array in kernel/catalogs/spell.lua and
-- kernel/catalogs/aura.lua, taken from `spell_chain` joined to `spell_template` in
-- tbcmangos.sqlite (MaNGOS TBC 2.4.3, 298389504 bytes). The database is gitignored, so this table
-- is the only form of that answer the offline suite -- or CI -- can see.
--
-- `chains`    -- `spell_chain` has rows: membership AND order are both proved.
-- `unchained` -- no `spell_chain` rows. Ids proved to exist, share one SpellName and ascend;
--                `completeness` says whether the database can also prove none is missing.
-- Regenerate with:  python3 sentinel/tools/regen_catalog_chain_fixture.py
-- Verify in place:  python3 sentinel/tools/regen_catalog_chain_fixture.py --check

return {
    source = "tbcmangos.sqlite (MaNGOS TBC 2.4.3) spell_chain JOIN spell_template",

    -- ------------------------------------------------------------------
    -- Proved by spell_chain: these arrays must match EXACTLY, in order.
    -- ------------------------------------------------------------------
    chains = {
        arcane_explosion = {
            ids = { 1449, 8437, 8438, 8439, 10201, 10202, 27080, 27082 },
            levels = { 14, 22, 30, 38, 46, 54, 62, 70 },
            names = { "Arcane Explosion" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4", "Rank 5", "Rank 6", "Rank 7", "Rank 8" },
        },
        arcane_intellect = {
            ids = { 1459, 1460, 1461, 10156, 10157, 27126 },
            levels = { 1, 14, 28, 42, 56, 70 },
            names = { "Arcane Intellect" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4", "Rank 5", "Rank 6" },
        },
        blessing_of_might = {
            ids = { 19740, 19834, 19835, 19836, 19837, 19838, 25291, 27140 },
            levels = { 4, 12, 22, 32, 42, 52, 60, 70 },
            names = { "Blessing of Might" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4", "Rank 5", "Rank 6", "Rank 7", "Rank 8" },
        },
        blizzard = {
            ids = { 10, 6141, 8427, 10185, 10186, 10187, 27085 },
            levels = { 20, 28, 36, 44, 52, 60, 68 },
            names = { "Blizzard" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4", "Rank 5", "Rank 6", "Rank 7" },
        },
        cone_of_cold = {
            ids = { 120, 8492, 10159, 10160, 10161, 27087 },
            levels = { 26, 34, 42, 50, 58, 65 },
            names = { "Cone of Cold" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4", "Rank 5", "Rank 6" },
        },
        conjure_food = {
            ids = { 587, 597, 990, 6129, 10144, 10145, 28612, 33717 },
            levels = { 6, 12, 22, 32, 42, 52, 60, 70 },
            names = { "Conjure Food" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4", "Rank 5", "Rank 6", "Rank 7", "Rank 8" },
        },
        conjure_water = {
            ids = { 5504, 5505, 5506, 6127, 10138, 10139, 10140, 37420, 27090 },
            levels = { 4, 10, 20, 30, 40, 50, 60, 65, 70 },
            names = { "Conjure Water" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4", "Rank 5", "Rank 6", "Rank 7", "Rank 8", "Rank 9" },
        },
        consecration = {
            ids = { 26573, 20116, 20922, 20923, 20924, 27173 },
            levels = { 20, 30, 40, 50, 60, 70 },
            names = { "Consecration" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4", "Rank 5", "Rank 6" },
        },
        corruption = {
            ids = { 172, 6222, 6223, 7648, 11671, 11672, 25311, 27216 },
            levels = { 4, 14, 24, 34, 44, 54, 60, 65 },
            names = { "Corruption" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4", "Rank 5", "Rank 6", "Rank 7", "Rank 8" },
        },
        curse_of_agony = {
            ids = { 980, 1014, 6217, 11711, 11712, 11713, 27218 },
            levels = { 8, 18, 28, 38, 48, 58, 67 },
            names = { "Curse of Agony" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4", "Rank 5", "Rank 6", "Rank 7" },
        },
        curse_of_weakness = {
            ids = { 702, 1108, 6205, 7646, 11707, 11708, 27224, 30909 },
            levels = { 4, 12, 22, 32, 42, 52, 61, 69 },
            names = { "Curse of Weakness" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4", "Rank 5", "Rank 6", "Rank 7", "Rank 8" },
        },
        dragons_breath = {
            ids = { 31661, 33041, 33042, 33043 },
            levels = { 50, 56, 64, 70 },
            names = { "Dragon's Breath" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4" },
        },
        drain_life = {
            ids = { 689, 699, 709, 7651, 11699, 11700, 27219, 27220 },
            levels = { 14, 22, 30, 38, 46, 54, 62, 69 },
            names = { "Drain Life" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4", "Rank 5", "Rank 6", "Rank 7", "Rank 8" },
        },
        drain_soul = {
            ids = { 1120, 8288, 8289, 11675, 27217 },
            levels = { 10, 24, 38, 52, 67 },
            names = { "Drain Soul" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4", "Rank 5" },
        },
        fire_blast = {
            ids = { 2136, 2137, 2138, 8412, 8413, 10197, 10199, 27078, 27079 },
            levels = { 6, 14, 22, 30, 38, 46, 54, 61, 70 },
            names = { "Fire Blast" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4", "Rank 5", "Rank 6", "Rank 7", "Rank 8", "Rank 9" },
        },
        fire_ward = {
            ids = { 543, 8457, 8458, 10223, 10225, 27128 },
            levels = { 20, 30, 40, 50, 60, 69 },
            names = { "Fire Ward" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4", "Rank 5", "Rank 6" },
        },
        fireball = {
            ids = { 133, 143, 145, 3140, 8400, 8401, 8402, 10148, 10149, 10150, 10151, 25306, 27070, 38692 },
            levels = { 1, 6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 60, 66, 70 },
            names = { "Fireball" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4", "Rank 5", "Rank 6", "Rank 7", "Rank 8", "Rank 9", "Rank 10", "Rank 11", "Rank 12", "Rank 13", "Rank 14" },
        },
        flamestrike = {
            ids = { 2120, 2121, 8422, 8423, 10215, 10216, 27086 },
            levels = { 16, 24, 32, 40, 48, 56, 64 },
            names = { "Flamestrike" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4", "Rank 5", "Rank 6", "Rank 7" },
        },
        frost_armor = {
            ids = { 168, 7300, 7301 },
            levels = { 1, 10, 20 },
            names = { "Frost Armor" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3" },
        },
        frost_nova = {
            ids = { 122, 865, 6131, 10230, 27088 },
            levels = { 10, 26, 40, 54, 67 },
            names = { "Frost Nova" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4", "Rank 5" },
        },
        frost_ward = {
            ids = { 6143, 8461, 8462, 10177, 28609, 32796 },
            levels = { 22, 32, 42, 52, 60, 70 },
            names = { "Frost Ward" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4", "Rank 5", "Rank 6" },
        },
        frostbolt = {
            ids = { 116, 205, 837, 7322, 8406, 8407, 8408, 10179, 10180, 10181, 25304, 27071, 27072, 38697 },
            levels = { 4, 8, 14, 20, 26, 32, 38, 44, 50, 56, 60, 63, 69, 70 },
            names = { "Frostbolt" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4", "Rank 5", "Rank 6", "Rank 7", "Rank 8", "Rank 9", "Rank 10", "Rank 11", "Rank 12", "Rank 13", "Rank 14" },
        },
        hammer_of_justice = {
            ids = { 853, 5588, 5589, 10308 },
            levels = { 8, 24, 40, 54 },
            names = { "Hammer of Justice" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4" },
        },
        hammer_of_wrath = {
            ids = { 24275, 24274, 24239, 27180 },
            levels = { 44, 52, 60, 68 },
            names = { "Hammer of Wrath" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4" },
        },
        ice_armor = {
            ids = { 7302, 7320, 10219, 10220, 27124 },
            levels = { 30, 40, 50, 60, 69 },
            names = { "Ice Armor" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4", "Rank 5" },
        },
        ice_barrier = {
            ids = { 11426, 13031, 13032, 13033, 27134, 33405 },
            levels = { 40, 46, 52, 58, 64, 70 },
            names = { "Ice Barrier" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4", "Rank 5", "Rank 6" },
        },
        immolate = {
            ids = { 348, 707, 1094, 2941, 11665, 11667, 11668, 25309, 27215 },
            levels = { 1, 10, 20, 30, 40, 50, 60, 60, 69 },
            names = { "Immolate" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4", "Rank 5", "Rank 6", "Rank 7", "Rank 8", "Rank 9" },
        },
        life_tap = {
            ids = { 1454, 1455, 1456, 11687, 11688, 11689, 27222 },
            levels = { 6, 16, 26, 36, 46, 56, 68 },
            names = { "Life Tap" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4", "Rank 5", "Rank 6", "Rank 7" },
        },
        mage_armor = {
            ids = { 6117, 22782, 22783, 27125 },
            levels = { 34, 46, 58, 69 },
            names = { "Mage Armor" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4" },
        },
        mana_shield = {
            ids = { 1463, 8494, 8495, 10191, 10192, 10193, 27131 },
            levels = { 20, 28, 36, 44, 52, 60, 68 },
            names = { "Mana Shield" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4", "Rank 5", "Rank 6", "Rank 7" },
        },
        polymorph = {
            ids = { 118, 12824, 12825, 12826 },
            levels = { 8, 20, 40, 60 },
            names = { "Polymorph" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4" },
        },
        scorch = {
            ids = { 2948, 8444, 8445, 8446, 10205, 10206, 10207, 27073, 27074 },
            levels = { 22, 28, 34, 40, 46, 52, 58, 65, 70 },
            names = { "Scorch" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4", "Rank 5", "Rank 6", "Rank 7", "Rank 8", "Rank 9" },
        },
        seal_of_command = {
            ids = { 20375, 20915, 20918, 20919, 20920, 27170 },
            levels = { 20, 30, 40, 50, 60, 70 },
            names = { "Seal of Command" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4", "Rank 5", "Rank 6" },
        },
        seal_of_righteousness = {
            ids = { 20154, 21084, 20287, 20288, 20289, 20290, 20291, 20292, 20293, 27155 },
            levels = { 1, 1, 10, 18, 26, 34, 42, 50, 58, 66 },
            names = { "Seal of Righteousness" },
            rank_labels = { "Rank 1", "Rank 1", "Rank 2", "Rank 3", "Rank 4", "Rank 5", "Rank 6", "Rank 7", "Rank 8", "Rank 9" },
        },
        shadow_bolt = {
            ids = { 686, 695, 705, 1088, 1106, 7641, 11659, 11660, 11661, 25307, 27209 },
            levels = { 1, 6, 12, 20, 28, 36, 44, 52, 60, 60, 69 },
            names = { "Shadow Bolt" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4", "Rank 5", "Rank 6", "Rank 7", "Rank 8", "Rank 9", "Rank 10", "Rank 11" },
        },
    },

    -- ------------------------------------------------------------------
    -- No spell_chain rows. Read `completeness` before trusting these.
    -- ------------------------------------------------------------------
    unchained = {
        frostbite_debuffs = {
            ids = { 11071, 12496, 12497 },
            levels = { 0, 0, 0 },
            names = { "Frostbite" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3" },
            completeness = "proved-by-SpellName+Attributes",
            same_name_same_attributes = { 11071, 12496, 12497 },
        },
        retribution_aura = {
            ids = { 7294, 10298, 10299, 10300, 10301, 27150 },
            levels = { 16, 26, 36, 46, 56, 66 },
            names = { "Retribution Aura" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4", "Rank 5", "Rank 6" },
            completeness = "proved-by-SpellName+Attributes",
            same_name_same_attributes = { 7294, 10298, 10299, 10300, 10301, 27150 },
        },
        vengeance_proc = {
            ids = { 20050, 20052, 20053, 20054, 20055 },
            levels = { 0, 0, 0, 0, 0 },
            names = { "Vengeance" },
            rank_labels = { "", "", "", "", "" },
            completeness = "UNPROVED -- SpellName+Attributes does not isolate this family",
            same_name_same_attributes = { 20050, 20052, 20053, 20054, 20055, 39445 },
        },
        vengeance_talent = {
            ids = { 20049, 20056, 20057, 20058, 20059 },
            levels = { 0, 0, 0, 0, 0 },
            names = { "Vengeance" },
            rank_labels = { "Rank 1", "Rank 2", "Rank 3", "Rank 4", "Rank 5" },
            completeness = "UNPROVED -- SpellName+Attributes does not isolate this family",
            same_name_same_attributes = { 16909, 16910, 16911, 16912, 16913, 20049, 20056, 20057, 20058, 20059 },
        },
        water_elemental_freeze = {
            ids = { 33395 },
            levels = { 50 },
            names = { "Freeze" },
            rank_labels = { "" },
            completeness = "proved-by-SpellName+Attributes",
            same_name_same_attributes = { 33395 },
        },
    },

    -- aura.lua array -> the spell.lua key it must be the same chain as.
    aura_aliases = {
        blessing_of_might_ranks = "blessing_of_might",
        frost_nova_debuffs = "frost_nova",
        ice_barrier_auras = "ice_barrier",
        mana_shield_auras = "mana_shield",
        polymorph_debuffs = "polymorph",
        retribution_aura_ranks = "retribution_aura",
        seal_of_command_ranks = "seal_of_command",
        seal_of_righteousness_ranks = "seal_of_righteousness",
        vengeance_proc_auras = "vengeance_proc",
    },

    -- Deliberately not rank chains. The test fails on any array missing from every
    -- section, so a new array cannot slip in unclassified.
    curated = {
        hard_immunity_auras = "hand-picked cross-class immunities: Divine Shield ranks 1-2 (642/1020) plus Ice Block (45438). Three spells, two families, one question.",
    },

    -- Must equal the concatenation of the named arrays, in this order.
    derived = {
        all_frozen_debuffs = { "frost_nova_debuffs", "frostbite_debuffs", "water_elemental_freeze" },
    },
}
