//! The zone/area catalog: id → display name, and area → parent zone.
//!
//! Backed by `sentinel/kernel/catalogs/zones.json`, which
//! `sentinel/tools/regen_zone_catalog.py` writes from `AreaTable.dbc` in the same run that writes
//! the Lua mirror and the spawn→zone index. The catalog is `include_str!`'d, not opened at
//! runtime: the DBC is not a build input and the QueryServer has no working directory it can rely
//! on (it is started from the repo root, from `SentinelQueryServer/`, and from `cargo test`).
//!
//! **This replaced a hand-committed 139-row Rust table.** That table listed only the distinct
//! positive `quest_template.ZoneOrSort` values, was generated by a tool that was described but not
//! committed, and could not name a zone the quest table never mentions — which
//! `GET /zone/{id}/spawns` needs on every request. One generated catalog, one committed generator,
//! no second copy to drift.
//!
//! Two callers, two questions:
//!
//! * [`zone_name`] answers `quest_template.ZoneOrSort`, an **overloaded** column. A positive value
//!   is an `AreaTable` id; a non-positive value is a *sort* bucket (class, profession, seasonal
//!   event) with no area behind it, so `<= 0` returns `""` rather than guessing, and
//!   `QuestSummary.zone` carries that empty string straight to the panel.
//! * [`zone_exists`] backs the 404 on `/zone/{id}/spawns`. "No spawns recorded here" and "there is
//!   no such zone" are different answers and the caller must be able to tell them apart.
//!
//! Ids are `AreaTable` ids throughout, so both sub-areas (9 "Northshire Valley") and zones
//! (12 "Elwynn Forest") resolve; [`zone_of`] collapses the former to the latter. Two ids can share
//! a name — 4095 and 4131 are both "Magisters' Terrace", the outdoor area and the instance — which
//! is the client's own data, not a de-duplication bug.

use serde::Deserialize;
use std::collections::HashMap;
use std::sync::OnceLock;

const ZONES_JSON: &str = include_str!("../../sentinel/kernel/catalogs/zones.json");

#[derive(Debug, Deserialize)]
struct RawCatalog {
    areas: Vec<RawArea>,
}

#[derive(Debug, Deserialize)]
struct RawArea {
    id: u32,
    name: String,
    /// `AreaTable.m_ParentAreaID`; `0` marks a top-level zone.
    parent: u32,
}

pub struct ZoneCatalog {
    names: HashMap<u32, String>,
    parents: HashMap<u32, u32>,
}

impl ZoneCatalog {
    /// How many areas the catalog carries. Pinned by a test: the row count moving means the
    /// catalog was regenerated against a different client, which changes what every id means.
    pub fn len(&self) -> usize {
        self.names.len()
    }
}

/// The parsed catalog, built once.
///
/// A malformed catalog panics here rather than degrading to "every zone is unnamed": it is a
/// committed generated artifact, so a parse failure means the tree is broken, not that the request
/// was.
pub fn catalog() -> &'static ZoneCatalog {
    static CATALOG: OnceLock<ZoneCatalog> = OnceLock::new();
    CATALOG.get_or_init(|| {
        let raw: RawCatalog = serde_json::from_str(ZONES_JSON)
            .expect("sentinel/kernel/catalogs/zones.json is malformed — regenerate the catalog");
        let mut names = HashMap::with_capacity(raw.areas.len());
        let mut parents = HashMap::with_capacity(raw.areas.len());
        for area in raw.areas {
            parents.insert(area.id, area.parent);
            names.insert(area.id, area.name);
        }
        ZoneCatalog { names, parents }
    })
}

/// The display name for an `AreaTable` id, or `""` when there is none.
///
/// Takes `i64` because its caller reads `quest_template.ZoneOrSort` straight out of SQLite, where
/// the value is routinely negative; converting at the call site would push the sort-bucket rule
/// out of this module.
pub fn zone_name(id: i64) -> &'static str {
    if id <= 0 {
        return "";
    }
    match u32::try_from(id) {
        Ok(id) => catalog().names.get(&id).map(String::as_str).unwrap_or(""),
        Err(_) => "",
    }
}

/// Whether the catalog carries this area/zone id at all.
pub fn zone_exists(id: u32) -> bool {
    catalog().names.contains_key(&id)
}

/// The zone an area belongs to — itself when the area *is* a zone. `None` for an unknown id.
pub fn zone_of(id: u32) -> Option<u32> {
    let parent = *catalog().parents.get(&id)?;
    Some(if parent == 0 { id } else { parent })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::db::test_db::open;

    #[test]
    fn the_catalog_carries_every_area_in_the_dbc() {
        // 1,643 is the AreaTable.dbc row count for 2.4.3. It moving means the catalog was
        // regenerated against a different client, which changes what every zone id means.
        assert_eq!(catalog().len(), 1643);
    }

    #[test]
    fn a_positive_zone_or_sort_names_its_zone() {
        assert_eq!(zone_name(9), "Northshire Valley");
        assert_eq!(zone_name(12), "Elwynn Forest");
        assert_eq!(zone_name(3483), "Hellfire Peninsula");
    }

    #[test]
    fn a_sort_bucket_is_not_a_zone() {
        // Quest 26 carries ZoneOrSort -263, a *sort* bucket. Naming it would invent a zone.
        assert_eq!(zone_name(-263), "");
        assert_eq!(zone_name(0), "");
        assert_eq!(zone_name(99_999_999), "");
    }

    #[test]
    fn an_area_collapses_to_its_zone_and_a_zone_to_itself() {
        assert_eq!(zone_of(9), Some(12), "Northshire Valley is in Elwynn Forest");
        assert_eq!(zone_of(12), Some(12), "Elwynn Forest is top level");
        assert_eq!(zone_of(99_999_999), None);
        assert!(zone_exists(12));
        assert!(!zone_exists(99_999_999));
    }

    #[test]
    fn every_zone_a_quest_names_resolves_to_a_name() {
        // The guarantee the deleted 139-row table asserted by construction, now checked against
        // the live snapshot instead of a frozen list: a catalog regenerated from a different
        // client, or a DB snapshot with new content, breaks here rather than silently rendering
        // blank zones in the quest search panel.
        let db = open();
        let zones = db
            .distinct_quest_zones()
            .expect("quest_template must be readable");
        assert!(zones.len() >= 130, "only {} positive zones", zones.len());
        let unnamed: Vec<i64> = zones
            .into_iter()
            .filter(|id| zone_name(*id).is_empty())
            .collect();
        assert!(unnamed.is_empty(), "unnamed quest zones: {unnamed:?}");
    }
}
