-- Test script for compiler pass 2 (implied actions)
-- Run with: luajit test_pass2.lua

package.path = package.path .. ";/home/levi/Projects/SentinelCore/sentinel/modules/quest/?.lua;" ..
               ";/home/levi/Projects/SentinelCore/?.lua"

local SourceAST = require("sentinel.modules.quest.source_ast")
local CompilerPass1 = require("sentinel.modules.quest.compiler_pass1")
local CompilerPass2 = require("sentinel.modules.quest.compiler_pass2")

local project_dir = "/home/levi/Projects/SentinelCore/sentinel/data/profiles/quests/example_project"

print("=== Testing Compiler Pass 2 (Implied Actions) ===")
print()

-- Step 1: Parse the project
print("Step 1: Parsing project...")
local parse_result = SourceAST:parse_project(project_dir)

if not parse_result.ok then
    print("FAILED: Parsing failed with errors:")
    for _, err in ipairs(parse_result.errors) do
        print("  -", err)
    end
    os.exit(1)
end

print("SUCCESS: Parsed project without errors")
print("Project name:", parse_result.ast.project.name)

-- Count operations and blueprints
local op_count = 0
for _ in pairs(parse_result.ast.operations) do op_count = op_count + 1 end
local bp_count = 0
for _ in pairs(parse_result.ast.blueprints) do bp_count = bp_count + 1 end
print("Number of operations:", op_count)
print("Number of blueprints:", bp_count)
print()

-- Step 2: Run Compiler Pass 1 (DB Resolution)
print("Step 2: Running Compiler Pass 1 (DB Resolution)...")
local pass1 = CompilerPass1.new()
local pass1_result = pass1:run(parse_result.ast)

if not pass1_result.ok then
    print("FAILED: Pass 1 failed with errors:")
    for _, err in ipairs(pass1_result.errors) do
        print("  -", err)
    end
    os.exit(1)
end

print("SUCCESS: Pass 1 completed without errors")

-- Inspect the operations to see if resolution worked
for op_name, op in pairs(pass1_result.ast.operations) do
    print("\nOperation:", op_name)
    for i, action in ipairs(op.actions) do
        print("  Action", i, "type:", action.action_type)
        if action.action_type == "TalkToNPC" then
            print("    Args:")
            for k, v in pairs(action.args) do
                print("      ", k, "=", v)
            end
            -- Check if we have the resolved ID and data
            if action.args.npc_id then
                print("    Resolved NPC ID:", action.args.npc_id)
                if action.args.npc_data then
                    print("    NPC Data: name=", action.args.npc_data.name, "zone_id=", action.args.npc_data.zone_id)
                end
            end
        end
    end
end
print()

-- Step 3: Run Compiler Pass 2 (Implied Actions)
print("Step 3: Running Compiler Pass 2 (Implied Actions)...")
local pass2 = CompilerPass2.new()
local pass2_result = pass2:run(pass1_result.ast)

if not pass2_result.ok then
    print("FAILED: Pass 2 failed with errors:")
    for _, err in ipairs(pass2_result.errors) do
        print("  -", err)
    end
    os.exit(1)
end

print("SUCCESS: Pass 2 completed without errors")

-- Inspect the operations to see if implied actions were added
print("\nAfter Pass 2 - Checking for implied actions:")
for op_name, op in pairs(pass2_result.ast.operations) do
    print("\nOperation:", op_name)
    for i, action in ipairs(op.actions) do
        print("  Action", i, "type:", action.action_type)
        if action.action_type == "TalkToNPC" then
            print("    Args:")
            for k, v in pairs(action.args) do
                print("      ", k, "=", v)
            end
            -- Check if we have the resolved ID and data
            if action.args.npc_id then
                print("    Resolved NPC ID:", action.args.npc_id)
                if action.args.npc_data then
                    print("    NPC Data: name=", action.args.npc_data.name, "zone_id=", action.args.npc_data.zone_id)
                end
            end
            -- Check for _debug field that might indicate compiler-generated actions
            if action._debug and action._debug.generated_by_compiler then
                print("    NOTE: This action was generated by the compiler")
            end
        end
    end
end

-- Also check blueprints
print("\nChecking blueprints for implied actions:")
for bp_name, bp in pairs(pass2_result.ast.blueprints) do
    print("\nBlueprint:", bp_name)
    for i, action in ipairs(bp.expands_to) do
        print("  Action", i, "type:", action.action_type)
        if action.action_type == "TalkToNPC" then
            print("    Args:")
            for k, v in pairs(action.args) do
                print("      ", k, "=", v)
            end
        end
    end
end

print()
print("=== Test completed successfully ===")