//! Project — the canonical, editable, single source of truth (ADR `02_DATA_MODEL` §4, ADR-201).
//!
//! Stored as a modular directory of JSON files (ADR `02_DATA_MODEL` §29). This struct is the
//! in-memory representation; `sentinel-project-loader` (Phase 3) handles split/merge I/O.

use chrono::Utc;
use serde::{Deserialize, Serialize};

use super::{
    area::Area,
    enums::{Class, CoordinateMode, Faction, Race, Severity},
    guide::GuideHeaders,
    npc::NPCReference,
    object::GameObjectReference,
    operation::Operation,
    quest::QuestReference,
    variable::Variable,
};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Project {
    pub metadata: ProjectMetadata,
    /// The guide-block header this project was imported from (`#name`, `#group`, `#subgroup`,
    /// `#version`, `#next`).
    ///
    /// Separate from [`ProjectMetadata`] on purpose: `metadata.name` is an editable project title
    /// a user may rename at will, while [`GuideHeaders::name`] is the guide *identity* that
    /// `#next` and `#include` resolve against. Empty for a project that was authored rather than
    /// imported.
    #[serde(default)]
    pub guide_headers: GuideHeaders,
    #[serde(default)]
    pub settings: ProjectSettings,
    #[serde(default)]
    pub variables: Vec<Variable>,
    #[serde(default)]
    pub npc_library: Vec<NPCReference>,
    #[serde(default)]
    pub quest_library: Vec<QuestReference>,
    #[serde(default)]
    pub object_library: Vec<GameObjectReference>,
    #[serde(default)]
    pub areas: Vec<Area>,
    pub operations: Vec<Operation>,
    /// Generated by the validator; never hand-edited (ADR `02_DATA_MODEL` §26).
    #[serde(default)]
    pub diagnostics: Vec<Diagnostic>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub import_metadata: Option<ImportMetadata>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ProjectMetadata {
    pub id: uuid::Uuid,
    pub name: String,
    #[serde(default)]
    pub author: String,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub version: String,
    pub schema_version: String,
    #[serde(default = "default_game_version")]
    pub game_version: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub faction: Option<Faction>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub race: Option<Race>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub class: Option<Class>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub minimum_level: Option<u8>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub maximum_level: Option<u8>,
    pub created_at: String,
    pub updated_at: String,
}

fn default_game_version() -> String {
    "2.4.3".to_string()
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ProjectSettings {
    #[serde(default)]
    pub auto_repair: bool,
    #[serde(default)]
    pub auto_vendor: bool,
    #[serde(default)]
    pub auto_train: bool,
    #[serde(default)]
    pub learn_flight_paths: bool,
    #[serde(default)]
    pub auto_hearth: bool,
    #[serde(default)]
    pub skip_optional: bool,
    #[serde(default)]
    pub stop_on_death: bool,
    #[serde(default)]
    pub stop_on_validation_errors: bool,
    #[serde(default)]
    pub compile_optimization: bool,
    #[serde(default)]
    pub coordinate_mode: CoordinateMode,
}

impl Default for ProjectSettings {
    fn default() -> Self {
        Self {
            auto_repair: false,
            auto_vendor: false,
            auto_train: false,
            learn_flight_paths: false,
            auto_hearth: false,
            skip_optional: false,
            stop_on_death: false,
            stop_on_validation_errors: false,
            compile_optimization: false,
            coordinate_mode: CoordinateMode::World,
        }
    }
}

/// Validator output. Never edited by hand (ADR `02_DATA_MODEL` §26).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Diagnostic {
    pub severity: Severity,
    pub code: String,
    pub message: String,
    /// Entity the diagnostic applies to (e.g. operation id, npc name).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub entity: Option<String>,
    /// Action the diagnostic applies to, when relevant.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub action: Option<String>,
}

/// Tracks import source to enable re-import while preserving edits (ADR `02_DATA_MODEL` §27).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ImportMetadata {
    pub importer: String,
    pub imported_at: String,
    pub source_file: String,
    pub checksum: String,
    pub guide_version: String,
}

// ---------------------------------------------------------------------------
// Directory-format index types (ADR `02_DATA_MODEL` §29)
// ---------------------------------------------------------------------------

/// Index entry for an operation in `project.json` (id + title only).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct OperationIndex {
    pub id: uuid::Uuid,
    pub title: String,
}

/// Index entry for an area in `project.json` (id + name only).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AreaIndex {
    pub id: uuid::Uuid,
    pub name: String,
}

/// Top-level structure written to `project.json` inside a `.sproject/` directory.
///
/// Operations and areas are stored as lightweight indices; the full data lives
/// in `operations/<id>.json` and `areas/<id>.json` respectively.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ProjectDirIndex {
    pub metadata: ProjectMetadata,
    #[serde(default)]
    pub guide_headers: GuideHeaders,
    #[serde(default)]
    pub settings: ProjectSettings,
    #[serde(default)]
    pub variables: Vec<Variable>,
    #[serde(default)]
    pub npc_library: Vec<NPCReference>,
    #[serde(default)]
    pub quest_library: Vec<QuestReference>,
    #[serde(default)]
    pub object_library: Vec<GameObjectReference>,
    #[serde(default)]
    pub operations: Vec<OperationIndex>,
    #[serde(default)]
    pub areas: Vec<AreaIndex>,
    #[serde(default)]
    pub diagnostics: Vec<Diagnostic>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub import_metadata: Option<ImportMetadata>,
}

impl From<&Project> for ProjectDirIndex {
    fn from(project: &Project) -> Self {
        Self {
            metadata: project.metadata.clone(),
            guide_headers: project.guide_headers.clone(),
            settings: project.settings.clone(),
            variables: project.variables.clone(),
            npc_library: project.npc_library.clone(),
            quest_library: project.quest_library.clone(),
            object_library: project.object_library.clone(),
            operations: project
                .operations
                .iter()
                .map(|op| OperationIndex {
                    id: op.id,
                    title: op.name.clone(),
                })
                .collect(),
            areas: project
                .areas
                .iter()
                .map(|a| AreaIndex {
                    id: a.id,
                    name: a.name.clone(),
                })
                .collect(),
            diagnostics: project.diagnostics.clone(),
            import_metadata: project.import_metadata.clone(),
        }
    }
}

impl ProjectDirIndex {
    /// Reassemble a full `Project` from the index + separately-read entity data.
    pub fn into_project(self, operations: Vec<Operation>, areas: Vec<Area>) -> Project {
        Project {
            metadata: self.metadata,
            guide_headers: self.guide_headers,
            settings: self.settings,
            variables: self.variables,
            npc_library: self.npc_library,
            quest_library: self.quest_library,
            object_library: self.object_library,
            areas,
            operations,
            diagnostics: self.diagnostics,
            import_metadata: self.import_metadata,
        }
    }
}

/// Convenience constructor for an empty project with fresh metadata.
pub fn new_project(name: impl Into<String>) -> Project {
    let now = Utc::now().to_rfc3339();
    Project {
        metadata: ProjectMetadata {
            id: uuid::Uuid::new_v4(),
            name: name.into(),
            author: String::new(),
            description: String::new(),
            version: "0.1.0".to_string(),
            schema_version: "1.0.0".to_string(),
            game_version: default_game_version(),
            faction: None,
            race: None,
            class: None,
            minimum_level: None,
            maximum_level: None,
            created_at: now.clone(),
            updated_at: now,
        },
        guide_headers: GuideHeaders::default(),
        settings: ProjectSettings::default(),
        variables: Vec::new(),
        npc_library: Vec::new(),
        quest_library: Vec::new(),
        object_library: Vec::new(),
        areas: Vec::new(),
        operations: Vec::new(),
        diagnostics: Vec::new(),
        import_metadata: None,
    }
}
