local Events = {
    ENTERED = "bg:entered",
    LEFT = "bg:left",
    MODULE_ENABLED = "bg:module_enabled",
    MODULE_DISABLED = "bg:module_disabled",
    STATE_CHANGED = "bg:state_changed",
    OBJECTIVE_SELECTED = "bg:objective_selected",
    OBJECTIVE_REACHED = "bg:objective_reached",
    COMBAT_HANDOFF_REQUESTED = "bg:combat_handoff_requested",
    COMBAT_HANDOFF_RECLAIMED = "bg:combat_handoff_reclaimed",
    RETREAT_REQUESTED = "bg:retreat_requested",
    QUEUE_POPUP_DETECTED = "bg:queue_popup_detected",
    QUEUE_KIND_INFERRED = "bg:queue_kind_inferred",
    QUEUE_JOIN_DISPATCHED = "bg:queue_join_dispatched",
    QUEUE_JOIN_CONFIRMED = "bg:queue_join_confirmed",
    QUEUE_JOIN_NOT_CONFIRMED = "bg:queue_join_not_confirmed",
    QUEUE_ACCEPT_ATTEMPT = "bg:queue_accept_attempt",
    QUEUE_ACCEPT_DISPATCHED = "bg:queue_accept_dispatched",
    QUEUE_ACCEPT_CONFIRMED = "bg:queue_accept_confirmed",
    QUEUE_ACCEPT_SKIPPED = "bg:queue_accept_skipped",
    QUEUE_ACTIVE_STATUS_STALE = "bg:queue_active_status_stale",
    LEAVE_GATE_OPENED = "bg:leave_gate_opened",
    LEAVE_ATTEMPT = "bg:leave_attempt",
    LEAVE_CONFIRMED = "bg:leave_confirmed",
    LEAVE_API_MISSING = "bg:leave_api_missing",
    LEAVE_MAX_ATTEMPTS_REACHED = "bg:leave_max_attempts_reached",
    FOLLOW_TARGET_CHANGED = "bg:follow_target_changed",
    COMBAT_ZONE_ENTERED = "bg:combat_zone_entered",
    COMBAT_ZONE_LEFT = "bg:combat_zone_left",
}

return Events
