[package]
name = "mmap-loader"
version.workspace = true
edition.workspace = true
description = "Navigation mesh (.mmap/.mmtile) file loader"

[dependencies]
detour = { path = "../detour" }
thiserror.workspace = true
byteorder.workspace = true
dashmap.workspace = true
parking_lot.workspace = true
tracing.workspace = true
